0: unlabled
1: backpack
2: base-cabinet
3: basket
4: bathtub
5: beam
6: beanbag
7: bed
8: bench
9: bike
10: bin
11: blanket
12: blinds
13: book
14: bottle
15: box
16: bowl
17: camera
18: cabinet
19: candle
20: chair
21: chopping-board
22: clock
23: cloth
24: clothing
25: coaster
26: comforter
27: computer-keyboard
28: cup
29: cushion
30: curtain
31: ceiling
32: cooktop
33: countertop
34: desk
35: desk-organizer
36: desktop-computer
37: door
38: exercise-ball
39: faucet
40: floor
41: handbag
42: hair-dryer
43: handrail
44: indoor-plant
45: knife-block
46: kitchen-utensil
47: lamp
48: laptop
49: major-appliance
50: mat
51: microwave
52: monitor
53: mouse
54: nightstand
55: pan
56: panel
57: paper-towel
58: phone
59: picture
60: pillar
61: pillow
62: pipe
63: plant-stand
64: plate
65: pot
66: rack
67: refrigerator
68: remote-control
69: scarf
70: sculpture
71: shelf
72: shoe
73: shower-stall
74: sink
75: small-appliance
76: sofa
77: stair
78: stool
79: switch
80: table
81: table-runner
82: tablet
83: tissue-paper
84: toilet
85: toothbrush
86: towel
87: tv-screen
88: tv-stand
89: umbrella
90: utensil-holder
91: vase
92: vent
93: wall
94: wall-cabinet
95: wall-plug
96: wardrobe
97: window
98: rug
99: logo
100: bag
101: set-of-clothing
